RHDM-390,RHDM-391: Workaround for ERRAI-1101
kiegroup/optaplanner-wb pull request #268
Opened 2018-03-28 13:52 UTC by yurloc

Alternative solution to #266.

Downside: creates '*_default.properties' even if it's not needed (i.e. code that doesn't use TranslationService).
Benefits:
* No maintenance - will automatically apply the workaround for new code that uses TranslationService or old code that is migrated to it.
* No risk of breaking Zanata integration.

What do you think? @manstis @mbarkley

2018-03-28 13:52 UTC, yurloc commented on pom.xml
> +                  <globmapper from="*Constants.properties" to="*Constants_default.properties"/>
Should we do the same for `*Messages.properties` too?

2018-03-28 15:48 UTC, yurloc commented on pom.xml
> +                  <globmapper from="*Constants.properties" to="*Constants_default.properties"/>
No, we don't generally use Messages.

2018-03-29 17:59 UTC, mbarkley requested changes
So this doesn't need to be merged now, correct?

2018-03-30 13:56 UTC, ge0ffrey commented
@mbarkley IIRC in the end, me and Jiri, agree to merge this, because we'll still have upstream dependencies that depend on the GWT 2.0 i18n instead of errai's.

2018-04-02 08:00 UTC, yurloc commented
@ge0ffrey I don't think it has to do with upstream dependencies. The Errai's TranslationService issue only affects code that uses it. Any code that uses GWT Messages and Constants approach is unaffected.

I think we need this workaround until we migrate completely to TranslationService or come up with similar final solution.

Closing this PR because we've agreed with @mbarkley to make the change in `kie-parent`.

2018-04-02 08:00 UTC, closed without merging